# Generated by Django 4.2.1 on 2023-06-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='tab_cash',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='tab_coins',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
