# Generated by Django 4.2.1 on 2023-06-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_tab_cash_account_tab_coins'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email_notify',
            field=models.BooleanField(default=True),
        ),
    ]
