# Generated by Django 4.2.1 on 2023-06-04 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_email_notify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email_notify',
            field=models.BooleanField(default=True, verbose_name='Notificação por email'),
        ),
        migrations.AlterField(
            model_name='account',
            name='tab_cash',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='tab_coins',
            field=models.IntegerField(blank=True),
        ),
    ]
