# Generated by Django 4.2.1 on 2023-06-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_email_notify_alter_account_tab_cash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='tab_cash',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='tab_coins',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
