# Generated by Django 4.2.1 on 2023-06-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_tab_cash_alter_account_tab_coins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='tab_cash',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='tab_coins',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
