# Generated by Django 4.2.1 on 2023-06-06 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', markdownx.models.MarkdownxField()),
                ('source', models.URLField(blank=True)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('post_edited_date', models.DateTimeField(auto_now=True)),
                ('tab_coins', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True)),
                ('comments', models.ManyToManyField(blank=True, related_name='child_comments', to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
