# Generated by Django 4.2.1 on 2023-06-04 17:47

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='source',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
