# Generated by Django 4.2.1 on 2023-06-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_post_date_post_post_edited_date_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tab_coins',
            field=models.IntegerField(default=0),
        ),
    ]
