# Generated by Django 4.2.1 on 2023-06-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_tab_coins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_edited_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
