# Generated by Django 4.2.1 on 2023-06-05 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models

import datetime


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0007_alter_post_post_date_alter_post_post_edited_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='description',
            field=markdownx.models.MarkdownxField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_comments', to='posts.comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime.today()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='post_edited_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='tab_coins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
