# Generated by Django 4.2.1 on 2023-06-05 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_comment_description_comment_parent_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='posts.post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='coments',
            field=models.ManyToManyField(blank=True, related_name='comments', to='posts.comment'),
        ),
    ]
