# Generated by Django 4.2.1 on 2023-06-05 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_comment_post_alter_post_coments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='coments',
            new_name='comments',
        ),
    ]
